<?php $this->layout('layouts/main') ?>
<?php $this->start('head') ?> 

<title>The magic of beauty</title>

 <?php $this->end() ?> 



<?php $this->start('content') ?> 

<h2>Авторизация в системе</h2>
<div class="content">
	<form method="post" ">
		<p>Логин</p>
	 	<p><input type="text" name="username"></p>
	 	<p>Пароль</p>
	 	<p><input type="text" name="password" ></p>
		<p><button>send</button></p> 
	 </form>
</div>
<?php if (isset($error)) : ?>
<p style="color:red;"><?= $error ?></p>
<?php endif; ?>

<?php $this->end() ?> 