<?php $this->layout('layouts/main') ?>
<?php $this->start('head') ?> 

<title>The magic of beauty</title>

 <?php $this->end() ?> 



<?php $this->start('content') ?> 
<h1><?= fenric('config::test')->get('title') ?></h1>

<h2>Welcome to Fashion World!</h2>

<p>Free template from Free CSS Templates released under free to use it for both commercial or personal use. In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula. Link back to my site in some way. Quisque dictum integer nisl risus sagittis convallis rutrum. In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula. Free template from Free CSS Templates released under free to use it for both commercial or personal use. In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula. Link back to my site in some way. Quisque dictum integer nisl risus sagittis convallis rutrum. In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula.</p>

<h2>Recent Articles</h2>

							<ul class="img-list">
								<li>
									<img alt="" src="/images/img1.jpg" />
									<h4><a href="#">Fashion and Style</a></h4>
									At our site you will find everything that deals with fashion: fashion news, profiles of designers and models, comprehensive runway slideshows etc.
								</li>
								<li>
									<img alt="" src="/images/img1.jpg" />
									<h4><a href="#">About Fashion Free Template</a></h4>
									Free 1028X768 Optimized Website Template from Templates.com! We really hope that you like this template and will use for your websites.
								</li>
								<li>
									<img src="/images/img1.jpg" >
									<h4><a href="#">Fashion Starts Here</a></h4>
									In this sample article you will read about everything that deals with the modern fashion trends.
								</li>
							</ul>


<?php $this->end() ?> 